/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'webonise' at '22/8/16 12:07 PM' with Gradle 3.0
 *
 * @author webonise, @date 22/8/16 12:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
