/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'webonise' at '22/8/16 12:07 PM' with Gradle 3.0
 *
 * @author webonise, @date 22/8/16 12:07 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
